# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'IBCM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Firebase - using version 9.6.0 which is compatible with Swift 5.7
  pod 'Firebase/Core', '~> 9.6.0'
  pod 'Firebase/Auth', '~> 9.6.0'
  pod 'Firebase/Firestore', '~> 9.6.0'
  pod 'Firebase/Storage', '~> 9.6.0'
  pod 'Firebase/Messaging', '~> 9.6.0'
  pod 'Firebase/Analytics', '~> 9.6.0'
  
  # Networking
  pod 'Alamofire', '~> 5.6.4' # Use version compatible with Swift 5.7
  pod 'Starscream' # For WebSocket
  
  # UI
  pod 'SnapKit'
  pod 'Kingfisher', '~> 7.6.2' # Use version compatible with Swift 5.7
  pod 'IQKeyboardManagerSwift'
  
  # Utils
  pod 'SwiftLint'
  
  target 'IBCMTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IBCMUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
