# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

# Point to the project file
project 'IBCM.xcodeproj'

target 'IBCM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Firebase - using a more stable version
  pod 'Firebase/Core', '~> 9.6.0'
  pod 'Firebase/Auth', '~> 9.6.0'
  pod 'Firebase/Firestore', '~> 9.6.0'
  pod 'Firebase/Storage', '~> 9.6.0'
  pod 'Firebase/Messaging', '~> 9.6.0'
  pod 'Firebase/Analytics', '~> 9.6.0'
  
  # Networking
  pod 'Alamofire', '~> 5.6.4'
  pod 'Starscream', '~> 4.0.6' # For WebSocket
  
  # UI
  pod 'SnapKit', '~> 5.6.0'
  pod 'Kingfisher', '~> 7.6.2'
  pod 'IQKeyboardManagerSwift', '~> 6.5.11'
  
  # Utils
  pod 'SwiftLint', '~> 0.50.3'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      
      # Fix for Xcode 15
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
      
      # For libraries that don't support arm64 simulators
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      
      # Fix code signing issues
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
    end
  end
  
  # Fix script phases sandboxing
  installer.aggregate_targets.each do |aggregate_target|
    aggregate_target.xcconfigs.each do |config_name, config_file|
      config_file.attributes['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
      xcconfig_path = aggregate_target.xcconfig_path(config_name)
      config_file.save_as(xcconfig_path)
    end
  end
end 