# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'IBCM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'
  pod 'Firebase/Analytics'
  
  # Networking
  pod 'Alamofire'
  pod 'Starscream' # For WebSocket
  
  # UI
  pod 'SnapKit'
  pod 'Kingfisher'
  pod 'IQKeyboardManagerSwift'
  
  # Utils
  pod 'SwiftLint'
  
  target 'IBCMTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IBCMUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end 