services:
  ai-service:
    build:
      context: .
      dockerfile: deployment/docker/Dockerfile.ai
    environment:
    - AUTO_LEARNING_ENABLED=true
    - AUTO_RETRAIN_HOURS=72
    - BATCH_SIZE=256
    - MAX_EPOCHS=25
    - MODEL_COMPLEXITY=low
    ports:
    - 8002:8002
    volumes:
    - ./data:/app/data
    - ./models:/app/models
  backend:
    build:
      context: .
      dockerfile: deployment/docker/Dockerfile.backend
    depends_on:
    - ai-service
    environment:
    - AI_SERVICE_URL=http://ai-service:8002
    - WORKERS=2
    ports:
    - 8001:8001
    volumes:
    - ./data:/app/data
    - ./models:/app/models
  frontend:
    build:
      context: .
      dockerfile: deployment/docker/Dockerfile.frontend
    depends_on:
    - backend
    - ai-service
    environment:
    - BACKEND_URL=http://backend:8001
    - AI_SERVICE_URL=http://ai-service:8002
    ports:
    - 8000:8000
    volumes:
    - ./data:/app/data
  mongodb:
    environment:
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=trading_ai_2024
    image: mongo:latest
    ports:
    - 27017:27017
    volumes:
    - mongodb_data:/data/db
version: '3.8'
volumes:
  data_volume: {}
  models_volume: {}
  mongodb_data: {}
