data_collection:
  batch_processing: 400.0
  cleanup_old_data_days: 90
  parallel_enabled: true
enabled: true
model_optimization:
  complexity: low
  ensemble_enabled: false
  parallel_training: false
  prediction_cache: true
system_optimization:
  auto_detected: true
  cpu_cores: 8
  memory_gb: 8.0
  performance_tier: STANDARD
training_schedule:
  batch_size: 256
  early_stopping: true
  interval_hours: 72
  max_epochs: 25
